language: python

python:
  - "2.7"

services:
  - redis-server

before_install:
  - sudo apt-get install libopencv-dev libtesseract-dev git cmake build-essential libleptonica-dev
  - sudo apt-get install liblog4cplus-dev libcurl3-dev

  - git clone https://github.com/openalpr/openalpr.git

install:
  - cd openalpr/src
  - mkdir build
  - cd build

  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_INSTALL_SYSCONFDIR:PATH=/etc ..

  - make
  - sudo make install

  - cd ../bindings/python
  - source make.sh
  - pip install .

  - cd ../../../../core

  - pip install -r requirements.txt
  - pip install .

before_script:
  - cd core

script:
  - py.test spec
